name: Tests

  on:
    push:
    pull_request:

  jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Install modules
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
        - run: npm --frozen-lockfile
        - name: Run tests
        - run: npm test
